# -*- coding: utf-8 -*-
"""Copia de computeSales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6gYc4jHFV0Wv3zeSEEX1Y8IG_aSBtPg
"""

import json
import time
from difflib import SequenceMatcher


def load_json_file(filename):
    """
    Load JSON data from a file.
    """
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            data = json.load(file)
        return data
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return {}
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in '{filename}'.")
        return {}


def similar(a, b):
    """
    Calculate the similarity ratio between two strings.
    """
    return SequenceMatcher(None, a, b).ratio()


def compute_total_cost(price_catalogue, sales_record):
    """
    Compute the total cost of sales.
    """
    total_cost = 0
    for sale in sales_record:
        product_name = sale["Product"]
        match_found = False
        for catalog_product in price_catalogue:
            similarity = similar(product_name, catalog_product["title"])
            if similarity >= 0.9:
                price = catalog_product["price"]
                quantity = sale["Quantity"]
                total_cost += price * quantity
                match_found = True
                break
        if not match_found:
            print(f"Warning: No match found for product '\
            {product_name}' in price catalogue.")
    return total_cost


def main(sales_record_file, price_catalogue_file='TC1.ProductList.json'):
    """
    Main function to compute total sales cost.
    """
    start_time = time.time()

    price_catalogue = load_json_file(price_catalogue_file)
    sales_record = load_json_file(sales_record_file)

    total_cost = compute_total_cost(price_catalogue, sales_record)

    end_time = time.time()
    elapsed_time = end_time - start_time

    print(f"Total cost of sales: ${total_cost:.2f}")
    print(f"Time elapsed: {elapsed_time:.2f} seconds")

    with open("SalesResults.txt", "w", encoding='utf-8') as results_file:
        results_file.write(f"Total cost of sales: ${total_cost:.2f}\n")
        results_file.write(f"Time elapsed: {elapsed_time:.2f} seconds\n")

main('TC1.Sales.json')

main('TC2.Sales.json')

main('TC3.Sales.json')

# pylint: disable = C0304