# -*- coding: utf-8 -*-
"""wordCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VtlS3hw1WOHfZFT82DcfRC9A2CzVtaOU
"""

# -*- coding: utf-8 -*-

import time
import string
import os

"""
Module to perform word frequency count on a given text file.
"""

# Assume the file is in the current working directory or a full path is provided
def process_file(file_path):
    """
    Process the given text file and return a list of words.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            words = file.read().split()
            return words
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return []

def count_words(words):
    """
    Count the frequency of each word in the given list of words.
    """
    word_count = {}
    for word in words:
        word = word.strip(string.punctuation).lower()
        if word:
            word_count[word] = word_count.get(word, 0) + 1
    return word_count

def print_results(word_count, elapsed_time):
    """
    Print the word frequency count and total count.
    """
    print("Word Frequency Count:")
    total_count = 0
    for word, count in word_count.items():
        print(f"{word}: {count}")
        total_count += count

    print("\nTotal Count:", total_count)
    print("Time Elapsed:", elapsed_time, "seconds")

def save_results(word_count, elapsed_time):
    """
    Save the word frequency count and elapsed time to a file.
    """
    with open('WordCountResults.txt', 'w', encoding='utf-8') as result_file:
        result_file.write("Word Frequency Count:\n")
        for word, count in word_count.items():
            result_file.write(f"{word}: {count}\n")
        result_file.write("\nTime Elapsed: " + str(elapsed_time) + " seconds\n")

def main(file_name):
    """
    Main function to perform word frequency count.
    """
    # Check if file_name is a path or just a filename
    if not os.path.isabs(file_name):
        # If just a filename, construct a path assuming it's in the current working directory
        file_path = os.path.join(os.getcwd(), file_name)
    else:
        # If an absolute path, use it directly
        file_path = file_name

    start_time = time.time()

    words = process_file(file_path)
    if not words:
        return

    word_count = count_words(words)

    end_time = time.time()
    elapsed_time = end_time - start_time

    print_results(word_count, elapsed_time)
    save_results(word_count, elapsed_time)

main('TC1.txt')

main('TC2.txt')

main('TC3.txt')

main('TC4.txt')

main('TC5.txt')

# pylint: disable=C0304